### ISSUE TITLE
Fix hold entry integration test

### ISSUE THREAD

**Issue by struktured** [holochain/lib3h#402]

**Comment by struktured** [comment]
```Rust
[TRACE] ghost_channel: send request RequestId("billyezgeO3OMrKu50BhgPv8x~")
[DEBUG] 

(billy).process() START
[TRACE] [legacy engine] process
[TRACE] ClientToLib3h::QueryEntry: QueryEntryData { space_address: HashString("appA"), entry_address: HashString("entry_addr_1"), request_id: "req_billy_2", requester_agent_id: HashString("billy"), query: "test_query" }
[TRACE] ghost_channel: send request RequestId("billyqD_7mcCFNOaa7Lrm7asV1")
[TRACE] (billy).process_concrete() did_work = true
[TRACE] [legacy engine] reserve "client_to_lib3_response_245EazEVjLFt17Mys7S58" for HandleQueryEntry(QueryEntryData { space_address: HashString("appA"), entry_address: HashString("entry_addr_1"), request_id: "req_billy_2", requester_agent_id: HashString("billy"), query: "test_query" })
[DEBUG] (billy).process() END - 3
[TRACE] (billy).process() handle_lib3h(HandleQueryEntry(QueryEntryData { space_address: HashString("appA"), entry_address: HashString("entry_addr_1"), request_id: "client_to_lib3_response_245EazEVjLFt17Mys7S58", requester_agent_id: HashString("billy"), query: "test_query" }))
[DEBUG] (billy).process() - DRAIN END


 srv_msg_list: [HandleQueryEntry(QueryEntryData { space_address: HashString("appA"), entry_address: HashString("entry_addr_1"), request_id: "client_to_lib3_response_245EazEVjLFt17Mys7S58", requester_agent_id: HashString("billy"), query: "test_query" })]

billy reply to own request:

thread 'test_two_memory_nodes_basic_suite' panicked at 'not yet implemented: Handle this case: FailureResult(GenericResultData { request_id: "req_billy_2", space_address: HashString("appA"), to_agent_id: HashString("billy"), result_info: "No entry found" })', crates/lib3h/src/engine/ghost_engine_wrapper.rs:212:20
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print|
```
