### ISSUE TITLE
linux ci flaky failure

### ISSUE THREAD

**Issue by neonphog** [holochain/lib3h#414]
https://circleci.com/gh/holochain/lib3h/2849?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
---- transport::websocket::actor::tests::test_websocket_transport stdout ----
thread 'transport::websocket::actor::tests::test_websocket_transport' panicked at 'called `Result::unwrap()` on an `Err` value: GhostError(Other("TransportError: Unknown error encountered: \'Operation not permitted (os error 1)\'."))', src/libcore/result.rs:1051:5
stack backtrace:
  <..snip..>
  12: lib3h::transport::websocket::actor::tests::test_websocket_transport
             at crates/lib3h/src/transport/websocket/actor.rs:515
```

**Comment by struktured** [comment]
Found another error using the flaky test finder:

```Rust
thread 'transport::websocket::actor::tests::test_websocket_transport_reconnect' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(Lib3hUri("wss://127.0.0.1:2026/"))`', crates/lib3h/src/transport/websocket/actor.rs:632:17
stack backtrace:
test transport::websocket::actor::tests::test_websocket_transport ... ok
Try 1 successful!
Try 2 successful!
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: lib3h::transport::websocket::actor::tests::test_websocket_transport_reconnect
             at crates/lib3h/src/transport/websocket/actor.rs:632
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/liballoc/boxed.rs:766
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  12: std::panicking::try
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/panicking.rs:275
  13: std::panic::catch_unwind
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/panic.rs:394
  14: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1466
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test transport::websocket::actor::tests::test_websocket_transport_reconnect ... FAILED


```
